export const hotelTypes = [
  "Budget",
  "Luxury",
  "Boutique",
  "Resort",
  "Hostel",
  "Business",
  "Family",
  "Eco-Friendly",
  "Pet-Friendly",
  "All-Inclusive",
  "Ski Resort",
  "Spa Hotel",
  "Boutique Hotel",
  "Extended Stay",
  "Bed and Breakfast",
  "Motel",
  "Vacation Rental",
  "Serviced Apartment",
];
